---
title: "Graficos Yani"
author: "RRSP"
date: "8/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(readxl)
library(lubridate)

```

```{r cache=TRUE}
# bases_articulos <- list.files(here('data', 'articulos'))
# 
# clasificador <- map(c('Class', 'Family'), 
#     ~read_excel(here::here('data', 'unspsc.xlsx'), sheet = .x) %>% 
#       mutate(across(everything(), as.character))
#     )
# 
# compras_adjudicadas <- readRDS(here('data', 'compras_adjudicadas.RDS'))
# 
# compras_articulos <- map(
#   bases_articulos,
#   ~read_excel(
#     here::here('data', 'articulos', .x)
#   )
# ) %>% 
#   bind_rows() %>% 
#   janitor::clean_names()
# 
# compras_articulos <- compras_adjudicadas %>% 
#   select(enlace_del_proceso, modalidad, objeto_del_proceso) %>% 
#   left_join(compras_articulos, .)
#  
# compras_articulos <- compras_articulos %>% 
#   mutate(
#     year = year(fecha_creacion),
#     mes = month(fecha_creacion),
#     codigo_unspcs = as.character(codigo_unspcs),
#     class = str_replace(codigo_unspcs, '..$', '00'),
#     family = str_replace(codigo_unspcs, '....$', '0000')
#     ) %>% 
#   left_join(clasificador[[1]]) %>% 
#   left_join(clasificador[[2]])
# 
# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')
# 
# yani_by_family <- compras_articulos %>%
#   filter(unidad_compra %in% instituciones_yani) %>% 
#   group_by(unidad_compra, family_desc) %>% 
#   summarise(
#     importe = sum(precio_unitario * cantidad)/1000000,
#     cantidad = sum(cantidad),
#     precio = mean(precio_unitario)
#   )
# 
# family_ym <- compras_articulos %>% 
#   filter(unidad_compra %in% instituciones_yani) %>%
#   mutate(fecha = floor_date(fecha_creacion, unit = 'month')) %>% 
#   group_by(fecha, unidad_compra, family_desc) %>% 
#   summarise(
#     importe = sum(precio_unitario * cantidad)/1000000,
#     cantidad = sum(cantidad),
#     precio = mean(precio_unitario)
#   )
#   
# family_ym %>% 
#   ungroup() %>% 
#   count(fecha) %>% 
#   ggplot(aes(x = fecha, y = n)) +
#   geom_line()

#save.image(here::here('data', 'informe_ws'))
load(here::here('data', 'informe_ws'))
```


```{r}
grafico_barra <- function(institucion) {
  
  yani_by_family %>% 
  filter(unidad_compra == institucion) %>% 
  filter(!is.na(family_desc)) %>% 
  slice_max(order_by = importe, n = 10) %>% 
  ungroup() %>% 
  mutate(family_desc = str_wrap(family_desc, 30)) %>%
  ggplot(aes(x = importe, y = fct_reorder(family_desc, importe))) +
  geom_col() +
  theme_light() +
  labs(x = "Millones de RR$", y = "Expenditure family",
       title = 'Compras acumuladas',
       subtitle = "2018 - 2020")
}


grid_compras_family <- function(institucion) {
  top_unidad_compra <- yani_by_family %>% 
  ungroup() %>% 
  filter(unidad_compra == institucion, !is.na(family_desc)) %>% 
  slice_max(order_by = importe, n = 10) %>% pull(family_desc)

plt_ym <- family_ym %>% 
  filter(unidad_compra == institucion, family_desc %in% top_unidad_compra) %>%
  mutate(importe = round(importe, 3),
         fecha = ymd(fecha),
         family_desc = fct_reorder(family_desc, importe)) %>% 
  ggplot(aes(x = fecha, y = importe), text = format(ymd(fecha), '%Y-%b')) +
  geom_line() +
  geom_point() +
  facet_wrap(~family_desc, scales = 'free_y', ncol = 2) +
  scale_x_date(labels = function(x) format(x, '%Y-%b')) +
  theme_minimal() +
  labs(x = NULL, y = 'Millones de RD$', title = "Compras mensuales por familia")

  plotly::ggplotly(plt_ym)
}
```




## Ministerio de Obras Públicas y Comunicaciones
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Ministerio de Obras Públicas y Comunicaciones')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Ministerio de Obras Públicas y Comunicaciones')
  
```


## Dirección General Impuestos Internos
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Dirección General Impuestos Internos')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Dirección General Impuestos Internos')
  
```

## Ministerio de Industria, Comercio y Mipymes
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Ministerio de Industria, Comercio y Mipymes')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Ministerio de Industria, Comercio y Mipymes')
  
```



## Seguro Nacional de Salud (SENASA)
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Seguro Nacional de Salud (SENASA)')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Seguro Nacional de Salud (SENASA)')
  
```


## Ministerio de Interior y Policía
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Ministerio de Interior y Policía')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Ministerio de Interior y Policía')
  
```


## Ministerio de defensa

***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Ministerio de Defensa')
```

```{r fig.height=12, fig.width=7}
grid_compras_family("Ministerio de Defensa")
  
```

## Contraloría Gral de la República

***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Contraloría Gral de la República')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Contraloría Gral de la República')
  
```

## Ministerio de la Mujer
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Ministerio de la Mujer')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Ministerio de la Mujer')
  
```

## MINISTERIO DE AGRICULTURA
***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('MINISTERIO DE AGRICULTURA')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('MINISTERIO DE AGRICULTURA')
  
```


## MINISTERIO DE AGRICULTURA

***
```{r}

# instituciones_yani <- c('Dirección General Impuestos Internos', 'Ministerio de Obras Públicas y Comunicaciones', 
#   'Ministerio de Industria, Comercio y Mipymes', 'Seguro Nacional de Salud (SENASA)', 
#   'Ministerio de Interior y Policía', 'Ministerio de Defensa', 'Contraloría Gral de la República',
#   'Ministerio de la Mujer', 'MINISTERIO DE AGRICULTURA', 'Plan Asistencia Social de la Presidencia')


grafico_barra('Plan Asistencia Social de la Presidencia')
```

```{r fig.height=12, fig.width=7}
grid_compras_family('Plan Asistencia Social de la Presidencia')
  
```




